In [1]:
import copy
from gc import set_debug
import heapq as hp
import numpy as np
from queue import PriorityQueue
import time
import math

In [2]:
def main():
    puzzle = [[1, 2, 3],
              [4, 5, 0],
              [7, 8, 6]]
    goal = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 0]]
    # print(puzzle)
    
    search(puzzle, goal, 1)
    
def search(puzzle, goal, heuristic):
    initial = Node(puzzle, cost(puzzle, goal, heuristic), 0)
    
    
    #nodes that we still need to explore
    #https://pythonguides.com/priority-queue-in-python/
    frontier = PriorityQueue()
    visited = []
    
    #initialize the frontier using the the initial state of the problem
    frontier.put(initial)
    
    while True:
        #if the frontier is empty then goal cant be found
        if frontier.empty():
            print("Could not find solution")
            break
            
        #pop from the frontier and look at next node
        current = frontier.get()
        
        #https://stackoverflow.com/questions/17870612/printing-a-two-dimensional-array-in-python
        print(np.matrix(current.puzzle))
        
        visited.append(current)
        #if the current node matchs goal then goal is found
        if current.puzzle == goal:
            print("Goal Found!")
            break
        
        #expand on current node and get children
        children = expand(current, goal, heuristic)
        
        # while children:
        #     t = children.pop()
        #     print(np.matrix(t.puzzle))
        
        #loop through the list of children
        while children:
            temp = children.pop()
            if not temp in visited:
                frontier.put(temp)
            
        
def expand(current, goal, heuristic):
    children = []
    blank = getblank(current)
    # print(blank)
    
    #http://www.idc-online.com/technical_references/pdfs/information_technology/Pairs_in_Python.pdf
    x, y = blank
    
    #move blank tile up
    if x > 0:
        child = copy.deepcopy(current)
        #swap the tiles
        #https://www.programiz.com/python-programming/examples/swap-variables
        child.puzzle[x][y], child.puzzle[x-1][y] = child.puzzle[x-1][y],child.puzzle[x][y]
        #increase depth
        child.gn += 1
        #calc the heuristic
        child.hn = cost(child.puzzle, goal, heuristic)
        #add child to children list
        children.append(child)
        
    #move blank tile down
    if x < len(current.puzzle)-1:
        child = copy.deepcopy(current)
        
        child.puzzle[x][y], child.puzzle[x+1][y] = child.puzzle[x+1][y],child.puzzle[x][y]
        child.gn += 1
        child.hn = cost(child.puzzle, goal, heuristic)
        
        children.append(child)
    
    #move blank tile left
    if y > 0:
        child = copy.deepcopy(current)
        
        child.puzzle[x][y], child.puzzle[x][y-1] = child.puzzle[x][y-1],child.puzzle[x][y]
        child.gn += 1
        child.hn = cost(child.puzzle, goal, heuristic)
        
        children.append(child)
    
    #move blank tile right
    if y < len(current.puzzle)-1:
        child = copy.deepcopy(current)
        
        child.puzzle[x][y], child.puzzle[x][y+1] = child.puzzle[x][y+1],child.puzzle[x][y]
        child.gn += 1
        child.hn = cost(child.puzzle, goal, heuristic)
        
        children.append(child)
        
    return children


def getblank(current):
    for i in range(len(current.puzzle)):
        for j in range(len(current.puzzle[i])):
            if 0 == current.puzzle[i][j]:
                pos = (i, j)
                break 
    return pos
    
def cost(puzzle, goal, heuristic):
    if heuristic == 1:
        return 0;
    elif heuristic == 2:
        return 0;
    else:
        return 0;
    
class Node:
    def __init__(self, puzzle, hn, gn):
            self.puzzle = puzzle
            self.hn = hn
            self.gn = gn
    def __lt__(self, other):
        return other.hn + other.gn > self.hn + self.gn
            
    
    
    
    
if __name__ == '__main__':
    main()

[[1 2 3]
 [4 5 0]
 [7 8 6]]
[[1 2 3]
 [4 0 5]
 [7 8 6]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
Goal Found!
